victoire_cms:
    widgets:
        list:
            class: "Victoire\\ListBundle\\Entity\\WidgetList"
            name: list
        listitem:
            class: "Victoire\\ListBundle\\Entity\\WidgetListItem"
            name: listitem
