victoire_cms:
    widgets:
        list:
            class: "Victoire\\ListBundle\\Entity\\WidgetList"
            name: list
        listitem:
            class: "Victoire\\ListBundle\\Entity\\WidgetListItem"
            name: listitem

jms_translation:
    configs:
        victoire_list_bundle:
            dirs: ["@VictoireListBundle"]
            output_dir: "@VictoireListBundle/Resources/translations"
