victoire_cms:
    widgets:
        listing:
            class: "Victoire\\ListingBundle\\Entity\\WidgetListing"
            name: listing
        listingitem:
            class: "Victoire\\ListingBundle\\Entity\\WidgetListingItem"
            name: listingitem
