victoire_core:
    widgets:
        listing:
            class: "Victoire\\Widget\\ListingBundle\\Entity\\WidgetListing"
            name: listing
        listingitem:
            class: "Victoire\\Widget\\ListingBundle\\Entity\\WidgetListingItem"
            name: listingitem
