services:
    victoire_core.widget_listing_content_resolver:
        class: Victoire\Widget\ListingBundle\Resolver\WidgetListingContentResolver
        tags:
            - { name: victoire_widget.widget_content_resolver, alias: Listing }

    #alias to the entity
    victoire.widget.listing:
        class: Victoire\Widget\ListingBundle\Entity\WidgetListing
    #alias to the form
    victoire.widget.form.listing:
        class: Victoire\Widget\ListingBundle\Form\WidgetListingType
        tags:
            - { name: form.type , alias: victoire_widget_form_listing}

