services:
    victoire_core.twig.widget_listing_manager:
        class: Victoire\Widget\ListingBundle\Widget\Manager\WidgetListingManager
        arguments: [@service_container]

    widget_listing_manager:
        alias: victoire_core.twig.widget_listing_manager
    widget_list_manager:
        alias: victoire_core.twig.widget_listing_manager

    victoire_core.twig.widget_listingitem_manager:
        class: Victoire\Widget\ListingBundle\Widget\Manager\WidgetListingItemManager
        arguments: [@service_container]

    widget_listingitem_manager:
        alias: victoire_core.twig.widget_listingitem_manager

    widget_listing.routing_loader:
        class: Victoire\Widget\ListingBundle\Routing\WidgetListingLoader
        tags:
            - { name: routing.loader }
