services:
    victoire_core.widget_listing_content_resolver:
        class: Victoire\Widget\ListingBundle\Resolver\WidgetListingContentResolver
        parent: victoire_widget.base_widget_content_resolver
        arguments:
            - "@request_stack"
            - "@=service('victoire_core.filter_chain').getFilters()"
        parent: victoire_widget.base_widget_content_resolver
        tags:
            - { name: victoire_widget.widget_content_resolver, alias: Listing }

    #alias to the entity
    victoire.widget.listing:
        class: Victoire\Widget\ListingBundle\Entity\WidgetListing
    #alias to the form
    victoire.widget.form.listing:
        class: Victoire\Widget\ListingBundle\Form\WidgetListingType
        tags:
            - { name: form.type }

    #alias to the listing item form
    victoire.widget.form.listingitem:
        class: Victoire\Widget\ListingBundle\Form\WidgetListingItemType
        tags:
            - { name: form.type }

    #tag listing Item as a widgetItem
    victoire.widget.listingitem:
        class: Victoire\Widget\ListingBundle\Entity\WidgetListingItem
        tags:
            - { name: victoire_widget.widget_item }

