services:
    victoire_cms.twig.widget_list_manager:
        class: Victoire\ListBundle\Widget\Manager\WidgetListManager
        arguments: [@service_container]

    widget_list_manager:
        alias: victoire_cms.twig.widget_list_manager

    victoire_cms.twig.widget_listitem_manager:
        class: Victoire\ListBundle\Widget\Manager\WidgetListItemManager
        arguments: [@service_container]

    widget_listitem_manager:
        alias: victoire_cms.twig.widget_listitem_manager

    widget_list.routing_loader:
        class: Victoire\ListBundle\Routing\WidgetListLoader
        tags:
            - { name: routing.loader }
